import type { Metadata } from "next";
import "./globals.css";
import { avenir, geistMono } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Siroj Traveloka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${avenir.variable} ${geistMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
